//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityAdvisor) DeepCopyInto(out *CapacityAdvisor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityAdvisor.
func (in *CapacityAdvisor) DeepCopy() *CapacityAdvisor {
	if in == nil {
		return nil
	}
	out := new(CapacityAdvisor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityAdvisor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityAdvisorList) DeepCopyInto(out *CapacityAdvisorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapacityAdvisor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityAdvisorList.
func (in *CapacityAdvisorList) DeepCopy() *CapacityAdvisorList {
	if in == nil {
		return nil
	}
	out := new(CapacityAdvisorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityAdvisorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityAdvisorSpec) DeepCopyInto(out *CapacityAdvisorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityAdvisorSpec.
func (in *CapacityAdvisorSpec) DeepCopy() *CapacityAdvisorSpec {
	if in == nil {
		return nil
	}
	out := new(CapacityAdvisorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityAdvisorStatus) DeepCopyInto(out *CapacityAdvisorStatus) {
	*out = *in
	out.Cluster = in.Cluster
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]PoolCapacity, len(*in))
		copy(*out, *in)
	}
	out.Recommendations = in.Recommendations
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityAdvisorStatus.
func (in *CapacityAdvisorStatus) DeepCopy() *CapacityAdvisorStatus {
	if in == nil {
		return nil
	}
	out := new(CapacityAdvisorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCapacity) DeepCopyInto(out *ClusterCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCapacity.
func (in *ClusterCapacity) DeepCopy() *ClusterCapacity {
	if in == nil {
		return nil
	}
	out := new(ClusterCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolCapacity) DeepCopyInto(out *PoolCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolCapacity.
func (in *PoolCapacity) DeepCopy() *PoolCapacity {
	if in == nil {
		return nil
	}
	out := new(PoolCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recommendations) DeepCopyInto(out *Recommendations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recommendations.
func (in *Recommendations) DeepCopy() *Recommendations {
	if in == nil {
		return nil
	}
	out := new(Recommendations)
	in.DeepCopyInto(out)
	return out
}
